name: Java Docker Images

on:
  push:
    branches:
      - java-docker-images

jobs:

  docker:

    runs-on: ubuntu-latest

    name: ${{ matrix.scenario.name }}

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: |
        docker build -t jdkimage docker
        docker history jdkimage
        docker run jdkimage java --version
